### ISSUE TITLE
memory error (python 2.7.11 32-bit)

### ISSUE THREAD

**Issue by wyattarnold** [DRI-WSWUP/cloud-free-scene-counts#2]
Ran into a memory error on [metadata_csv_fitler.py](https://github.com/Open-ET/cloud-free-scene-counts/blob/master/metadata_csv_filter.py) here:

`input_df = pd.read_csv(csv_path, parse_dates=[date_col])`

I was running python 2.7 32-bit. 

Tried with python 3.5 64-bit, and it ran fine.

**Comment by cgmorton** [comment]
Closing for now since it seems like the changes to reduce memory usage are working.
