### ISSUE TITLE
make_quicklook_list.py not counting first clear scene each year

### ISSUE THREAD

**Issue by beamerj** [DRI-WSWUP/cloud-free-scene-counts#3]
When I run make_quicklook_list.py and output clear_scene_counts.txt it consistently misses counting the first clear scene of each year, but counts the remaining scenes for the path_row and year. 

I'm not sure if it has to do with how the counts = defaultdict(dict) is structured (line 142), or the try and except routine (lines 148-151). 

Any tips on getting this to work correctly?

**Comment by cgmorton** [comment]
Thanks for catching this bug Jordan!  I updated make_quicklook_list.py.  Would you mind giving it a try?

**Comment by beamerj** [comment]
It works now! Thanks Charles
